name: Deploy Automático en AWS # Nombre del workflow CD

on:
  workflow_run:
    workflows: ["Publicar en Docker Hub"] # Se ejecuta después del CI
    types:
      - completed # Solo cuando el workflow anterior termina

jobs:
  deploy:
    runs-on: ubuntu-latest # GitHub usa una máquina Linux temporal

    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Solo despliega si el CI fue exitoso

    steps:
      - name: Desplegar en servidor vía SSH
        uses: appleboy/ssh-action@master # Conecta por SSH a tu EC2
        with:
          host: ${{ secrets.SERVER_IP }} # IP pública de la EC2
          username: ${{ secrets.SSH_USER }} # Usuario: ec2-user
          key: ${{ secrets.AWS_SSH_KEY }} # Clave privada guardada en GitHub Secrets
          script: |
            docker pull devopsjulio/devioz-proyecto:latest # Descarga la última imagen desde Docker Hub

            docker stop mi-sitio || true # Detiene el contenedor anterior si existe
            docker rm mi-sitio || true # Elimina el contenedor anterior si existe

            docker run -d --restart unless-stopped -p 80:80 --name mi-sitio devopsjulio/devioz-proyecto:latest # Levanta la nueva versión y la deja auto-reiniciable

            docker ps # Muestra el contenedor corriendo como evidencia

          # 1. Descarga la nueva imagen actualizada desde Docker Hub
        
          # 2. Detiene y elimina el contenedor anterior si existe
 

          # 3. Lanza la nueva versión del contenedor
          # Mapeamos el puerto 80 del servidor al puerto 80 del contenedor
         