# El nombre de este proceso automático
name: Publicar en Docker Hub

# ¿CUÁNDO se va a ejecutar?
on:
  push:
    branches: [ "main" ] # Solo cuando hagas "push" a la rama main

# ¿QUÉ va a hacer? (Los trabajos o 'jobs')
jobs:
  build-and-push:
    runs-on: ubuntu-latest # GitHub nos presta una computadora con Linux gratis
    
    steps:
      # 1. Copia tu código de GitHub a la máquina virtual
      - name: Checkout del código
        uses: actions/checkout@v3

      # 2. CALIDAD DE CÓDIGO (Linter): Revisa errores y avisa la línea exacta del fallo
      - name: Instalar HTMLHint
        run: npm install -g htmlhint

      - name: Ejecutar Linter HTMLHint
        run: htmlhint **/*.html

      # 3. AUTENTICACIÓN SEGURA: Inicia sesión en Docker Hub usando tus llaves ocultas
      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. CONSTRUCCIÓN DE LA IMAGEN LOCAL: La prepara en la máquina de GitHub para evaluarla
      - name: Construir imagen local para pruebas
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false # No la sube aún, primero se analiza
          tags: devopsjulio/devioz-proyecto:latest

      # 5. SEGURIDAD DE INFRAESTRUCTURA (Trivy): Escanea virus o fallos críticos en la imagen
      - # 5. SEGURIDAD DE INFRAESTRUCTURA (Trivy): Escanea virus o fallos críticos en la imagen
      - name: Escanear imagen Docker con Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'devopsjulio/devioz-proyecto:latest'
          format: 'table'
          exit-code: '1' # Si encuentra algo CRÍTICO, rompe el proceso y avisa al equipo
          ignore-unfixed: true # <-- AGREGA ESTA LÍNEA EXACTAMENTE AQUÍ (Respeta los espacios)
          severity: 'CRITICAL'

      # 6. DESPLIEGUE SEGURO: Solo si pasó el Linter y pasó Trivy, se publica en internet
      - name: Subir imagen limpia a Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: devopsjulio/devioz-proyecto:latest