name: Publicar en Docker Hub # Nombre del workflow CI

on:
  push:
    branches: [ "main" ] # Se ejecuta solo cuando haces push a main

jobs:
  build-and-push:
    runs-on: ubuntu-latest # GitHub usa una máquina Linux temporal

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3 # Descarga tu código del repositorio

      - name: Instalar HTMLHint
        run: npm install -g htmlhint # Instala el linter HTML

      - name: Ejecutar Linter HTMLHint
        run: htmlhint "**/*.html" # Revisa errores en archivos HTML

      - name: Construir imagen Docker local
        run: docker build -t devopsjulio/devioz-proyecto:latest . # Crea la imagen sin subirla todavía

      - name: Escanear imagen Docker con Trivy
        uses: aquasecurity/trivy-action@master # Escanea vulnerabilidades en la imagen con trivy
        with:
          image-ref: 'devopsjulio/devioz-proyecto:latest' # Imagen que será analizada
          format: 'table' # Muestra el resultado en tabla
          exit-code: '1' # Si hay vulnerabilidad crítica, falla el pipeline
          ignore-unfixed: true # Ignora fallos sin solución disponible
          severity: 'CRITICAL' # Solo bloquea vulnerabilidades críticas

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v2 # Login seguro usando Secrets
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Usuario Docker Hub
          password: ${{ secrets.DOCKER_PASSWORD }} # Token/clave Docker Hub

      - name: Subir imagen limpia a Docker Hub
        run: docker push devopsjulio/devioz-proyecto:latest # Sube la imagen solo si pasó linter y Trivy